---
title: "Anomaly Detection in High Dimensional Data"
author:
- familyname: Talagala
  othernames: Priyanga Dilini
  address: Department of Econometrics and Business Statistics, Monash University, Australia, and \newline ARC Centre of Excellence for Mathematics and Statistical Frontiers
  email: dilini.talagala@monash.edu
  correspondingauthor: true
- familyname: Hyndman
  othernames: Rob J.
  address: Department of Econometrics and Business Statistics, Monash University, Australia, and \newline ARC Centre of Excellence for Mathematics and Statistical Frontiers
- familyname: Smith-Miles
  othernames: Kate
  address: School of Mathematics and Statistics, University of Melbourne, Australia, and \newline ARC Centre of Excellence for Mathematics and Statistical Frontiers
abstract: "The HDoutliers algorithm is a powerful unsupervised algorithm for detecting  anomalies in high-dimensional data, with a strong theoretical foundation. However, it suffers from  some limitations that significantly hinder its performance level, under certain circumstances. In this article, we propose an algorithm that addresses these limitations. We define an anomaly as an observation that deviates markedly from the majority with a large distance gap.  An approach based on extreme value theory is used for the anomalous threshold calculation. Using various synthetic and real datasets, we demonstrate the wide applicability and usefulness of our algorithm, which we call the `stray` algorithm. We also demonstrate how this algorithm can assist in  detecting anomalies present in other data structures using feature engineering. We show the situations where the stray algorithm outperforms the HDoutliers algorithm  both in accuracy and computational time.  This framework is implemented in the open source R package `stray`. "
keywords: "Extreme value theory, High-dimensional data, Nearest neighbour searching, Temporal data, Unsupervised outlier detection"
wpnumber: no/yr
jelcodes: C1, C8, C55
blind: false
cover: false
toc: false
bibliography: references.bib
biblio-style: authoryear-comp
output:
  MonashEBSTemplates::workingpaper:
    fig_caption: yes
   # fig_height: 12
   # fig_width: 18
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE)
# Make sure you have the latest version of rmarkdown and bookdown
#devtools::install_github("rstudio/rmarkdown")
#devtools::install_github("rstudio/bookdown")
```


```{r main, child='main.Rmd'}
```


